image: yopapp/build-image-java
pipelines:
  branches:
    develop:
    - step:
        caches:
        - gradle
        script:
        - bash ./gradlew build
        - ARTIFACT_NAME=$BITBUCKET_COMMIT.zip
        - aws s3 cp build/distributions/*zip s3://$AWS_S3_BUCKET/$ARTIFACT_NAME --region $AWS_S3_REGION
        - if ! $(aws elasticbeanstalk describe-application-versions --region $AWS_EB_REGION --application-name $AWS_EB_APP --version-labels $BITBUCKET_COMMIT|grep -q 'VersionLabel'); then aws elasticbeanstalk create-application-version --region $AWS_EB_REGION --version-label $BITBUCKET_COMMIT --application-name $AWS_EB_APP --source-bundle S3Bucket=$AWS_S3_BUCKET,S3Key=$ARTIFACT_NAME; fi;
        - aws elasticbeanstalk update-environment --region $AWS_EB_REGION --version-label $BITBUCKET_COMMIT --environment-name $AWS_EB_ENV_DEVEL
        - if ! $(aws elasticbeanstalk describe-application-versions --region $AWS_EB_REGION --application-name $AWS_EB_APP_CKNET --version-labels $BITBUCKET_COMMIT|grep -q 'VersionLabel'); then aws elasticbeanstalk create-application-version --region $AWS_EB_REGION --version-label $BITBUCKET_COMMIT --application-name $AWS_EB_APP_CKNET --source-bundle S3Bucket=$AWS_S3_BUCKET,S3Key=$ARTIFACT_NAME; fi;
        - aws elasticbeanstalk update-environment --region $AWS_EB_REGION --version-label $BITBUCKET_COMMIT --environment-name $AWS_EB_CKNET_ENV_DEVEL
    master:
    - step:
        caches:
        - gradle
        script:
        - bash ./gradlew build
        - ARTIFACT_NAME=$BITBUCKET_COMMIT.zip
        - aws s3 cp build/distributions/*zip s3://$AWS_S3_BUCKET/$ARTIFACT_NAME --region $AWS_S3_REGION
        - if ! $(aws elasticbeanstalk describe-application-versions --region $AWS_EB_REGION --application-name $AWS_EB_APP --version-labels $BITBUCKET_COMMIT|grep -q 'VersionLabel'); then aws elasticbeanstalk create-application-version --region $AWS_EB_REGION --version-label $BITBUCKET_COMMIT --application-name $AWS_EB_APP --source-bundle S3Bucket=$AWS_S3_BUCKET,S3Key=$ARTIFACT_NAME; fi;
        - aws elasticbeanstalk update-environment --region $AWS_EB_REGION --version-label $BITBUCKET_COMMIT --environment-name $AWS_EB_ENV_PROD

