version: '2.1'
services:
  localstack:
    image: localstack/localstack:1.1.0
    ports:
      - "4566:4566"
      - "4583:4566"
      - "4571:4571"
    environment:
      - SERVICES=ssm
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "/private/tmp/localstack:/tmp/localstack"